# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 06:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf_cnpj', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('nome_empresa', models.TextField(blank=True, null=True)),
                ('sum', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
    ]
